### ISSUE TITLE
Allow to specify what is current time

### ISSUE THREAD

**Issue by valodzka** [rmm5t/jquery-timeago#10]
Currently it is hardcoded as browser current time, but it would be usefull to allow user specify that is current time (something like this http://gist.github.com/398904).

In my case it necessary because I have to display intervals like '2 seconds' ago and very often browser time is different from server time in couple of seconds. With this patch I can specify current time as server time and display correct intervals.

**Comment by AlexeyKosov** [comment]
Why is it still open?
