### ISSUE TITLE
Timeago value not generated in IE or Chrome for certain cases

### ISSUE THREAD

**Issue by ironalex** [rmm5t/jquery-timeago#209]
Please see my test code on: http://jsfiddle.net/orokusaki/bn0q7mkj/
Press Run and then click Post multiple times quickly in a row and you will see some generated divs contain timeago values and others do not. I don't understand why. If someone could please assist I would be extremely grateful

**Comment by rmm5t** [comment]
Sorry. Please ask questions like this on a site like [StackOverflow](http://stackoverflow.com/) instead. GitHub Issues have a different purpose, and it's unlikely anyone will find the time to help debug your issue here.

**Comment by ironalex** [comment]
Hi rmm5t - sorry I already have asked it there (several times) however no one seems to be able to answer me. Please could you advise where to go from here being that no one seems to know.

**Comment by rmm5t** [comment]
Please consider making your example easier to digest. A simpler and more direct use case will encourage easier feedback and help than the one you have now. Right now, that jsfiddle is a bit of a hodge-podge mess.

For example, I looked at your jsfiddle to see if I could help, but immediately decided it wasn't worth my time to parse what you were trying to accomplish.

**Comment by ironalex** [comment]
Thanks rmm5t I appreciate your feedback. Honestly I can't think of a simpler way of putting across my code, I've stripped it back as far as I know how. Is there anything you can suggest like how I can make my jsfiddle less of a mess as I'm fairly new at coding in general. Not trying to be difficult at all.

**Comment by rmm5t** [comment]
> Is there anything you can suggest like how I can make my jsfiddle less of a mess 

Yes. Use jsfiddle properly. Properly put your javascript in the javascript field. Put your CSS in the CSS field. Add Timeago as an "External Resource" in jsfiddle. Properly indent your code. Take the time to actually write a concise use-case (e.g. you still have PHP in your jsfiddle example).

> Honestly I can't think of a simpler way of putting across my code.

Consider looking for a good software mentor -- either find a friend who is willing to help or pay for a mentor on a site like [Codementor](https://www.codementor.io/)

**Comment by ironalex** [comment]
Thank you rmm5t! Also I'm extremely grateful to and have lots of admiration for you and your fellows at MIT who have generously given away your hard work. Seriously impressed by your achievements and generousity
