### ISSUE TITLE
How do i return the original date if time distance is more than 24 hours

### ISSUE THREAD

**Issue by Allan-iam** [rmm5t/jquery-timeago#210]
I would like to to display something like the time passed to if the the time distance is more than a day.

Thanks you

**Comment by rmm5t** [comment]
Sorry. Please ask questions like this on a site like [StackOverflow](http://stackoverflow.com/) instead. GitHub Issues have a different purpose.

Meanwhile, see the `cutoff` setting. Also see #21 and #194.

**Comment by Allan-iam** [comment]
Okay thanks you for the response
