### ISSUE TITLE
time in the future displayed as in the past

### ISSUE THREAD

**Issue by doppynl** [rmm5t/jquery-timeago#215]
I've got a situation where I need to show in how much time a match starts, so the calculation needs to be done to the future.

But when I currently do this:

```
jQuery.timeago.settings.allowPast = false;
jQuery.timeago.settings.allowFuture = true;
jQuery(document).ready(function() {
    $("abbr.timeago").timeago();
});
```

It shows the time for me as "X minutes ago". Where the X is correct, only it is in the future.

After some testing it seems like it is not checked if the date is actually in the past or future, just the other prefix/suffix is used.

Is this intentional?
Or am I doing something wrong?

**Comment by rmm5t** [comment]
That's tough to say without more information. Are you sure the `settings` are actually getting set before `timeago()` is being called? (i.e. Are you sure the code is exactly as specified above?)

This library has a test suite, and it's all passing. Furthermore, I ran a sanity check with the same settings that you have, and it behaved as expected.

**Here's a screenshot of that test:**
![timeago-future-test](https://cloud.githubusercontent.com/assets/740/6446331/9c40b5c2-c0c7-11e4-9759-d6fe5bce544b.png)

**Comment by doppynl** [comment]
My report wasn't entirely correct. Probably due to me needing to use both a relative period to some time in the past as in the future. Causing me to mess things up.

See the fiddle for the problem:
http://jsfiddle.net/zbk113t4/1/
The date set is in the future, but it is displayed as in the past. Even though allowFuture is set to false.

The problem in the code lies here:
https://github.com/rmm5t/jquery-timeago/blob/a6fcbec3fe6bb3f522be2968bdc18abf9c4b6ca3/jquery.timeago.js#L83
I think there needs to be an additional check there.

Something like this:

      if(!this.settings.allowFuture && distanceMillis < 0) {
        return this.settings.strings.inFuture;
      }

**Comment by rmm5t** [comment]
I'd consider a pull-request, only because there's that weird edge case for the opposite condition.

But, why do you have dates in the future and want `allowFuture = false`?

**Comment by doppynl** [comment]
It is used for an application that monitors a 12-hour volleybal tournament. Matches start every 15minutes.

I'm displaying starttime + "starting in X minutes".
When the starttime is in the past I want that to disappear.

I'm also displaying endtimes + "finished X minutes ago".
When the endtime is in the future, I don't want to see it. The moment the endtime is in the past it may display how long ago the match ended.

Why do I want dates in the future and allowFuture is false?
Because then it will instantly show "finished 1 minute ago" when the match just finished.

**Comment by rmm5t** [comment]
Thanks for the added detail and use-case explanation. Please submit a PR with the new logic and a test case to cover this scenario, and I'll pull it in and release a new version.
