### ISSUE TITLE
[question] convert to full timeago "x years, y months, z days ago" not only "years/months/days" ago

### ISSUE THREAD

**Issue by flashios09** [rmm5t/jquery-timeago#217]
Hi,
Thanks @rmm5t for this awesome jquery plugin :+1: 
Sorry for my bad english :(

Is it possible to convert a datetime to **full timeago** like this
**2015-01-25 03:37:46** to "**2 months, one day, 5 hours and 10 minutes ago**"

now it only convert **2015-01-25 03:37:46** to "**2 months ago**"

Thanks

**Comment by rmm5t** [comment]
@flashios09 Yes, it's possible, but you'd have to create an entirely new locale to get this kind of support. You'd also have to run all the math calculations yourself, but you could reuse the same function for all of the locale substitutions. All of the locale substitutions can accept a string or a function. 

For an example of function substitutions, the Russian or Czech locales (as compared to the English locale) are a good starting point. 

English: https://github.com/rmm5t/jquery-timeago/blob/master/locales/jquery.timeago.en.js

Russian: https://github.com/rmm5t/jquery-timeago/blob/master/locales/jquery.timeago.ru.js
Czech: https://github.com/rmm5t/jquery-timeago/blob/master/locales/jquery.timeago.cs.js

The first argument passed to each function is the number value for that unit of measure, but the second argument is the total number of milliseconds difference between the timestamp and the current time.  You would want to rely on the 2nd argument for your custom locale.

**Comment by SandyMaya** [comment]
Hello ,
Thank you @rmm5t for your plugins.
I need some extra features in your plugins .
right now it gives '1 day ago' and I would like to have like this 'yesterday at 10:00am' with time.
_'2 days ago' -> 'day before yesterday at 10:00am'
and '3 days ago' -> '3 days ago at 10:00am' and so on_
Actually there is only text changes for yesterday and day after that and an additional time to the text. 
So to get this, how can i change locale?

Thank you!!!
