### ISSUE TITLE
Incomplete documentation

### ISSUE THREAD

**Issue by slavafomin** [rmm5t/jquery-timeago#218]
Hello!

The documentation looks incomplete right now. Some features are not documented at all. Are you planning to update it?

**Comment by rmm5t** [comment]
In an ideal world, everything would be unicorns and rainbows, but welcome to open source. Pull-requests are always welcome (especially for documentation improvements).

**Comment by slavafomin** [comment]
@rmm5t, yes, I can understand you perfectly )

It just looks odd for such a popular library to have an incomplete docs. I'm not using it myself, so I just can't divert time to improve it. Maybe someone else will give a hand.

**Comment by rmm5t** [comment]
> It just looks odd for such a popular library to have an incomplete docs.

Thanks and agreed, but I maintain dozens (maybe hundreds) of both closed-source and open-source projects. Plus, I run two (soon three) businesses and have three kids. There's only so much time. Priorities and whatnot.

> I'm not using it myself

Wait. What? :anguished:
