### ISSUE TITLE
Running timeAgo on multiple Date fields that change and are added/removed from DOM while others are simply changed values

### ISSUE THREAD

**Issue by jasondavis** [rmm5t/jquery-timeago#221]
I have a Project Management App with opens a Project Task record when clicked on into a **Task Modal**

The Task Modal is only 1 DIV in the DOM which is re-used over and over again for every single Task record on the page that is clicked on.

What this means, is that different Date/Time fields in my Task Modal will constantly be changing for each Task record.

For example when I launch a Task Modal,  I set up a `timeAgo()` instance on my Task Modal **Due Date** field like this:  

    $('#duedatetimeago').text(jQuery.timeago(dueDate));

When the Task Modal is Closed, I then need to clear out this value which is easy enough `$('#duedatetimeago').text('');` however I believe the `timeAgo()` instance will remain running in the background.

Now when a new Task Modal is launched, it will again run the code `$('#duedatetimeago').text(jQuery.timeago(dueDate));`  even though in the background the existing one is still running somewhere!

This is just One example of many that I will be running in my Task Modal!  The image below gives a better picture as to what I am up against...

You will see my before mentioned **Due Date field**  but also in the far right is a list of comments which will be loaded for each Task Modal.  There DateTime value will not only be different for each Task record, but also the number of them will be different for each record as 1 tak might have 0 comments and another might have 100!

[View full size image](http://i.imgur.com/jKGXTij.png)
![timaeago](http://i.imgur.com/jKGXTij.png)

So I am not 100% sure my best route to make this efficiently work.

Is there a way to destroy all my timeAgo() instances when my Task Modal is closed so that I can then rebuild the ones that are needed when a new Task Modal is opened?

If not, then I request such a feature please.  

I would be extremely grateful to any help

**Comment by rmm5t** [comment]
> Is there a way to destroy all my timeAgo() instances when my Task Modal is closed so that I can then rebuild the ones that are needed when a new Task Modal is opened?

Yes, call `$(...).timeago("dispose")`

**Comment by jasondavis** [comment]
Thanks and sorry i'm a little new to JS, appreciate it though
