### ISSUE TITLE
question about Math.round in inWords function.

### ISSUE THREAD

**Issue by bung87** [rmm5t/jquery-timeago#229]
I am using django developing a site,at the backend I try to use 'django.contrib.humanize' ,It has a function called timesince adapted from http://web.archive.org/web/20060617175230/http://blog.natbat.co.uk/archive/2003/Jun/14/time_since.
when the datetime turns out to '11 days,23 hours',at frontend the jquery-timeago turns it to '12 days ago',so I checked the code source file,Math.round appears 6 times,so when the variable days equels to some like '11.xx' ,it may turns to 12 days,I think using Math.floor would be better.it always not wrong.

**Comment by rmm5t** [comment]
These are "fuzzy" timestamps. Furthermore, the behavior was designed to exactly match the rounding done by the helper function, `time_ago_in_words`, in the Rails framework. 

11 days, 23 hours is effectively 12 days when it comes to _fuzzy_ / _humanized_ time.

Sorry, I don't anticipate making any changes here.

**Comment by bung87** [comment]
I digged some articles just now,found this http://apidock.com/rails/v3.2.13/ActionView/Helpers/DateHelper/distance_of_time_in_words
and I think you're right,I misunderstood it,I may change the backend render function.
