### ISSUE TITLE
Can this be made to "[time] to go"?

### ISSUE THREAD

**Issue by Taapo** [rmm5t/jquery-timeago#234]
I see a lot of plugins and libraries that create a "time ago" plugin, but most of them are not supporting "time to go" dates. Is there a possibility that this could be added to this plugin?

**Comment by rmm5t** [comment]
Sure thing. To allow for future dates, set this before calling `timeago()` on your elements:

```javascript
jQuery.timeago.settings.allowFuture = true;
```

If you also want it to suffix the timestamps with _"...to go"_ instead of _"...from now"_ change this setting as well:

```javascript
jQuery.timeago.settings.strings.suffixFromNow = "to go";
```
