### ISSUE TITLE
Change Timezone

### ISSUE THREAD

**Issue by kingpabel** [rmm5t/jquery-timeago#249]
Actually i need to change timezone,i mean i wanna set a timezone.Is there any way to do this?

**Comment by rmm5t** [comment]
Timeago handles all time zones out and any combination of server vs client time zone. Just use properly formatted ISO 8601 timestamps.
https://en.wikipedia.org/wiki/ISO_8601

**Comment by kingpabel** [comment]
@rmm5t  thank for your reply
where i set timezone,can you give me an example please?

**Comment by rmm5t** [comment]
I did give you a example. Read the ISO 8602 spec. Specifically the time
zone section.

**Comment by e-oz** [comment]
Heh, what an example of arrogant answer. 
There is no ISO 8602 and there is no "time zone section" in 8601.

To answer for future readers, you should add space and timezone to your date string.
Example: `2018-01-31 15:37:00` becomes `2018-01-31 15:37:00 UTC`.

**Comment by rmm5t** [comment]
@e-oz Sorry, that "8602" was a typo when I wrote that email, but the previous comment pointing at the Wikipedia article should have trumped that anyway.

> To answer for future readers: you should add space and timezone to your date string.

What an arrogant assumption. 😜

No, sorry. Future readers should ignore this. @e-oz's timestamp examples are not correct. Even though they work given the current parser, they're not guaranteed to work in the future.

Instead, this would be a proper ISO 8601 timestamp that this library expects: `2018-01-31T15:37:00Z` (for UTC time) or `2018-01-31T09:30:57-07:00` (e.g. for any other time zone).
