### ISSUE TITLE
a trick, switch views

### ISSUE THREAD

**Issue by glensc** [rmm5t/jquery-timeago#250]
hi

i've implemented in my project a trick, that if you click on the element, it will switch between timeago and the original.

https://github.com/eventum/eventum/commit/12de217df73c1e8588226fdca46c0a6a7b718fc4

i'm just wondering that you may wish to add that trick to your docs as well.

**Comment by rmm5t** [comment]
Good idea and tip. Feel free to add it to the wiki: https://github.com/rmm5t/jquery-timeago/wiki

**Comment by glensc** [comment]
so, you do not see any issues with it? for example some timers or etc if the content is dynamic?

**Comment by rmm5t** [comment]
For the generic use-case of timeago, it looks fine. Once timeago is initialized on an element, timeago no longer uses the `title` attribute and instead relies on internal data attributes that it sets after parsing the original ISO8601 timestamp.
