### ISSUE TITLE
Time Ago Not Working on Dynamic Generated Timestamp from Ajax Get Request

### ISSUE THREAD

**Issue by masterpowers** [rmm5t/jquery-timeago#254]
I tried Using Time Ago its Working Fine if i Use The Sample
But when i Am Using the Plugin in the Data i Fetch from an Ajax Call
The Result is The Time Stamp Still not Change to Time Ago

**Comment by rmm5t** [comment]
You still need to initialize timeago on the new dynamic elements that are loaded in the page.

**Comment by abdul-baten** [comment]
asasasas

**Comment by rmm5t** [comment]
> asasasas

@abdul-baten That was totally enlightening. Thank you. 😕
