### ISSUE TITLE
Move <time> to top of doc instead of <abbr>

### ISSUE THREAD

**Issue by mahemoff** [rmm5t/jquery-timeago#255]
Context: https://twitter.com/rmm5t/status/672054648711155713

Placeholder for me to add this later.

**Comment by talha-asad** [comment]
+1

**Comment by iandevlin** [comment]
+1

**Comment by tchalvak** [comment]
Makes sense, I use <time> everywhere and it works well.

**Comment by rmm5t** [comment]
This was long overdue. Docs updated to prefer `<time>`. Thanks for the nudges everyone.

**Comment by mahemoff** [comment]
:v: awesome
