### ISSUE TITLE
Add a way to exclude suffix or prefix

### ISSUE THREAD

**Issue by TwentyOneSolutions** [rmm5t/jquery-timeago#258]
If you want to set the string of seconds ago to "Just now", or 24 hours ago to "Yesterday", you can not do it with the current implementation.

A better way would have been to add `%suffix` and `%prefix` to the string just as you have `%d`, so that instead of `about %d seconds` you would actually set `about %d seconds %suffix`.

The problem is that changing this now would not be backward compatible, so my suggestion is to be able to state "no-suffix", e.g. to set seconds to "Just now" you would set the string for seconds to read `Just now %ns` and if the code detects `%ns` then it would not add the suffix (same for prefix).

**Comment by rmm5t** [comment]
"Yesterday" is not compatible with page caching and hence the goals of this project. It's dependent on when midnight occurred in the time zone of the client viewing the page. i.e. It's been covered many times before (search past issues), but "yesterday" will never be a feature of timeago. 

You're correct that "just now" isn't really feasible with the current implementation, but I think it's the only edge case that also applies to the goals of the project. However, getting pedantic over the possibilities of "just now" vs "less than a minute ago" for something that is only meant to represent fuzzy time is probably a waste of effort.

> A better way would have been to add %suffix and %prefix to the string just as you have %d, so that instead of about %d seconds you would actually set about %d seconds %suffix.

Hindsight, I agree, but yeah, breaking backwards compatibility doesn't make this change worth it.

> my suggestion is to be able to state "no-suffix", e.g. to set seconds to "Just now" you would set the string for seconds to read Just now %ns and if the code detects %ns then it would not add the suffix (same for prefix).

Sorry, while that might be the only backwards compatible suggestion, it's not worth the effort for just a rare edge case that adds very little benefit. Difficultly with future proofing becomes the new trade off here, and I don’t think it's worth it.
