### ISSUE TITLE
Make RefreshMillis (Update Time) Dynamic

### ISSUE THREAD

**Issue by masterpowers** [rmm5t/jquery-timeago#259]
This is the Default Refresh Time in Settings For All Unit of Time
Seconds , Minutes , Hours, Day, Months,

```
settings: {
      refreshMillis: 60000,
```

Is there a Possibility to make it Dynamic
If the Human Readable time for example is
last 1 sec ago... It Should Update Based On Seconds
So it will update every 1 sec and will change on the next seconds

If the Human Readable time for example is last minute ago...
It Should Be Updated Every 60 Secs or the Default in this Plugin.

And So On....

**Comment by rmm5t** [comment]
Thanks for the suggestion, and sorry for the lack of response for so long. I'm not sure there's a lot of benefit to this.  The default fuzzy timestamps don't change to anything more relevant than "a few seconds ago" and "one minute ago," so there's little benefit to a faster refresh, even early on.
