### ISSUE TITLE
option to have tooltip change only

### ISSUE THREAD

**Issue by glensc** [rmm5t/jquery-timeago#266]
based on https://github.com/rmm5t/jquery-timeago/wiki/Tips#switch-between-time-ago-and-back
made dates clickable, my user's aren't still happy.

so i tried to make that by default it's not turned on, so that click activates it:

```javascript
    // jquery timeago
    var $timeago = $('abbr.timeago');
    // on click toggle between views
    var timeago_toggle = function () {
        var $el = $(this);
        var old = $el.attr('title');
        $el.attr('title', $el.text());
        $el.text(old);
    };

        // enable only on click
        $timeago.click(function () {
            $(this)
                .timeago()
                .unbind('click')
                .click(timeago_toggle);
        })
```
https://github.com/eventum/eventum/commit/91e4f66477c35c5c7c86cded76f5b9aca480057a

it works well, but tooltip now is  supposed to show relative date, but instead it's iso6861 timestamp stright from html, which is rather ugly. so, do you have suggestion here or maybe add some kind of support for this?

![image](https://cloud.githubusercontent.com/assets/199095/12277153/96304e22-b982-11e5-9dd4-ba326df7cd83.png)

**Comment by rmm5t** [comment]
Well, you're not enabling timeago until after the first click, so of course, this is the behavior I would expect you to see.  This is partly because you're using the deprecated `<abbr>` microformatted tags (iso8601 stored in `title`attribute) instead of HTML5 `<time>` tags (iso8601 timestamp stored in `datetime` attribute). Tooltips are driven by the `title` attribute.

**Comment by glensc** [comment]
well, the `<abbr>` i took from your site when i implemented it. so you suggest i switch `<abbr>` to `<time>` and then browser render `title=""` itself properly?

**Comment by rmm5t** [comment]
I'm suggesting that if you switch to <time> tags, you'll have more leeway
in how you handle title attributes.

Of course, I don't understand why timeago isn't enabled until after the
first click. That's the only time that you're tooltips will be off from
what you're expecting in your original example.

**Comment by glensc** [comment]
people wanted relative dates off by default. so i made them activated by click only. but the solution i came up (pasted here) with resulted that "title" attribute shows raw iso8601 timestamp from html.

but i had an idea what timeago plugin could have attribute to change only "title" leave "text" part intact (therefore this ticket).

so in other words, would like timeago to be active, but leave text part intact, only change "title" to contain relative date.

i hope this clears up my intention

**Comment by rmm5t** [comment]
Yes, this better clarifies your intention, but Tooltips are meant for
getting more specific information, not less specific. I think you've got it
backwards.

Sorry, I don't think I'm willing to make any changes to the core library to
support exactly what your trying to accomplish. It's a strange edge case
that no one else would ever use.

**Comment by glensc** [comment]
the intention is to have timeago "off" for unsatisfied users, but still have it present to do something "useful", in this case have tooltip contain relative date

**Comment by rmm5t** [comment]
> the intention is to have timeago "off" for unsatisfied users, but still have it present to do something "useful", in this case have tooltip contain relative date

I understand. I just totally disagree with this as a UX/UI paradigm. Your stakeholders have it backwards, and I can't compromise on this kind of feature. Adding a feature for one use-case when thousands do it the other way doesn't sound like something I'd like to support long-term. However, you've got what you need to get closer to your desired outcome if you use the `<time>` tag.

**Comment by glensc** [comment]
changed to:

```html
<time class="timeago" title="2015-05-10T07:55:21Z">Sun, 10 May 2015, 10:55:21 EEST</time>
```

yet (chrome) tooltip still shows raw "2015-05-10T07:55:21Z"

**Comment by rmm5t** [comment]
> changed to:
```html
<time class="timeago" datetime="2015-05-10T07:55:21Z" title="YOUR TOOLTIP!">Sun, 10 May 2015, 10:55:21 EEST</time>
```

**FTFY**. Next time, please [read the docs](http://timeago.yarp.com/) and read [my comments](https://github.com/rmm5t/jquery-timeago/issues/266#issuecomment-171098412) detailing what's necessary. Also read the HTML5 docs for the `<time>` tag and [how it was designed](http://microformats.org/wiki/datetime-design-pattern) to replace the `<abbr>` microformat.
