### ISSUE TITLE
Update Japanese translation

### ISSUE THREAD

**Issue by yoshihara** [rmm5t/jquery-timeago#268]
Hi,
we use this plugin in Japanese, but I want to fix Japanese transation for "n month(s) ago".

e.g. ) `Japanese translation for "1 month ago" (n = 1)`
now translation) "1 月前"
correct transation) "1 ヶ月前"

So now translations miss "ヶ", so I want to add it to some translation in `locales/jquery.timeago.ja.js`. (c.f. [google translation](https://translate.google.co.jp/?ie=UTF-8&hl=ja&client=tw-ob#en/ja/1%20month%20ago ))

If you would like to do, I prepare to make pull request. Could you tell me what you think about it, please?

**Comment by rmm5t** [comment]
Yes. A pull request would be appreciated. Thank you.

**Comment by yoshihara** [comment]
Thank you! I make pull request ASAP.
