### ISSUE TITLE
Vanilla Java Script

### ISSUE THREAD

**Issue by neuropass** [rmm5t/jquery-timeago#278]
Would it be possible to have pure JS plugin?
Looks like now days this could be possible.

**Comment by rmm5t** [comment]
Yes, it's definitely possible, but unlikely to happen anytime soon. I've been brainstorming about a v2 rewrite of timeago. There would still always be a jquery wrapper, but I'll consider a vanilla JS core -- that is if I ever get around to the rewrite.
