### ISSUE TITLE
Nuget package is at 1.1.1

### ISSUE THREAD

**Issue by jrkd** [rmm5t/jquery-timeago#281]
Is it possible to update the NuGet.org package for jquery-timeago to include the latest release? 

It's currently at 1.1.1.

Had an issue where I installed from Nuget and became really confused when the cutoff setting wasn't functioning only to find out that the site's demos were using uptodate and I definitely wasn't.

**Comment by rmm5t** [comment]
I never published there, and I don't plan to. 

You'll have to find this guy who took the name and published my library there without making it part of this source repository's process as new versions are released. 
https://www.nuget.org/profiles/masenkablast

I don't have a NuGet account, but I suspect that I won't have permission to publish under a taken name. 

If you want automatic publishing there, a PR with automatic publishing there would be necessary.
