### ISSUE TITLE
Using timeago with server timestamp

### ISSUE THREAD

**Issue by aHumanBeing** [rmm5t/jquery-timeago#283]
Hi,

If I'm able to provide the server timestamp to the client, would it be possible to determine _timeago_ using server timestamp (as the start time) and another future time stamp?

I apologize in advance if this is the inappropriate place to ask such questions.

Thank you

**Comment by rmm5t** [comment]
May I ask why you want to use a server timestamp?  Do you not trust the client to have the correct time?

**Comment by aHumanBeing** [comment]
Unfortunately, I do not trust the client to have the correct time 100%. My thoughts were that if I could somehow use the server time, it wouldn't matter what the client time would be.

**Comment by rmm5t** [comment]
The way I see it...if you can't trust the client time and you want super accurate timestamps, then you shouldn't be using a fuzzy timestamp library like this. 

Furthermore, it's probably not worth the brain cycles to mistrust the client time in a world where most every operating system automatically synchronizes time with network time. 

Sorry, the feature you're looking for doesn't exist yet, and it's not something that I'd be eager to incorporate into the library.

**Comment by zieru** [comment]
whyyyyyyy
-_-
