### ISSUE TITLE
packagist

### ISSUE THREAD

**Issue by hexathos** [rmm5t/jquery-timeago#298]
Hi,

you are providing files for integration into composer, but your repository isn't listed on packagist.org , would you mind adding it? 
Sure anyone could do, but if there is no service hook in your github settings, it won't update newer versions by itself.

**Comment by rmm5t** [comment]
That `composer.json` was part of a submitted PR (#256), but I just submitted a new package: https://packagist.org/packages/rmm5t/jquery-timeago

I also configured github webhooks so it will update automatically from here on out.
