### ISSUE TITLE
Proper pluralization support

### ISSUE THREAD

**Issue by jhass** [rmm5t/jquery-timeago#300]
Providing separate translations for `one` and `other` is not enough to properly accommodate all languages. As per Unicode CLDR Pluralization rules, keys up to `one`, `two`, `few`, `many`, `other` should be supported, see http://cldr.unicode.org/index/cldr-spec/plural-rules

One way that would spare binding the library to a specific i18n system, is to just provide callbacks instead of doing the interpolation inside the library.

**Comment by jhass** [comment]
Nvm, looks like this is already possible.

**Comment by rmm5t** [comment]
Callbacks are already supported for different locales. Take the Russian locale in the `locales` directory as an example. 

Am I misunderstanding something about this request?
