### ISSUE TITLE
How to convert '1 day ago' to 'yesterday at 10:00am' as an example.

### ISSUE THREAD

**Issue by SandyMaya** [rmm5t/jquery-timeago#301]
Hello ,
Thank you @rmm5t for your plugins.
I need some extra features in your plugins .
right now it gives '1 day ago' and I would like to have like this 'yesterday at 10:00am' with time.
'2 days ago' -> 'day before yesterday at 10:00am'
and '3 days ago' -> '3 days ago at 10:00am' and so on
Actually there is only text changes for yesterday and day after that and an additional time to the text. 
So to get this, how can i change locale?

Thank you!!!

**Comment by rmm5t** [comment]
See #66

See comments on the commit from this patch:
http://github.com/brianmhunt/jquery-timeago/commit/dfbef678758da942127fc60a10638f12dd2c3ee2#commitcomment-97584
