### ISSUE TITLE
Doesn't seem to work

### ISSUE THREAD

**Issue by leecollings** [rmm5t/jquery-timeago#312]
I'm not sure what I';m doing wrong, I believe I've followed everything in the docs corrrectly. Nothing seems to be standing out, but I'm sure I must be doing something wrong as others seem to not have this issue (looking through the issues).

FYI, I'm using this on Wordpress, and outputting using the following:
`<time class="timeago" timedate="<?php echo get_the_date('c'); ?>"><?php echo get_the_date(); ?></time>`

The script is being called after jQuery, and using the standard example to initalise:
`$('time.timeago').timeago();`

But the output I see doesn't seem to be using the plugin, although it is loading, as the `title` attribute is being added:
`<time class="timeago" timedate="2016-12-12T10:04:44+00:00" title="12th December 2016">12th December 2016</time>`

See an example on http://development.bellavou.co.uk/blog/

**Comment by rmm5t** [comment]
https://developer.mozilla.org/en-US/docs/Web/HTML/Element/time#Attributes

It's the `datetime` attribute, not `timedate`.
