### ISSUE TITLE
Wrong calculation

### ISSUE THREAD

**Issue by yinsw** [rmm5t/jquery-timeago#315]
Is the below intended or the calculation is wrong?

Current PC time is : **2017-03-23 11:10AM**

Date 1: **2017-03-21 18:00:00**
`<time class="timeago" datetime="2017-03-21 18:00:00">2017-03-21 18:00:00</time>`
It shows: "**a day ago**"

Date 2: **2017-03-21 15:00:00**
`<time class="timeago" datetime="2017-03-21 15:00:00">2017-03-21 15:00:00</time>`
It shows "**2 days ago**"

**Comment by rmm5t** [comment]
1. All bets are off because you're not using ISO 8601 time stamps and haven't specified time zones. Please read the docs. 
2. It's intended. Read the source for the hour window difference for "a day ago" vs "two days ago."
