### ISSUE TITLE
Locales are not UMD compatible

### ISSUE THREAD

**Issue by m90** [rmm5t/jquery-timeago#318]
Installing `timeago` from npm will install the locale files, but they are not require-able as they rely on `jQuery` to be available on the global object, throwing

```
  Uncaught ReferenceError: jQuery is not defined
```

Is there any way of requiring these definitions? In case not would you accept a PR that wraps these files in a proper UMD wrapper?

**Comment by rmm5t** [comment]
While I really dislike UMD wrappers, I don't have a good enough reason to deny this request. If you'd like to submit a PR that wraps all the locales, I'd be happy to review and merge it. Much appreciated.

**Comment by rmm5t** [comment]
Closed by #319
