### ISSUE TITLE
Locales should require jquery-timeago

### ISSUE THREAD

**Issue by andrejpavlovic** [rmm5t/jquery-timeago#323]
It often happens that timeago locale gets loaded before jquery-timeago because the lack of dependency on jquery-timeago in the locale files
```javascript
require(['jquery', 'jquery-timeago', 'jquery-timeago-ca'], function($) {/* get a loading error */});
```

The locale files should include a dependecy on jquery-timeago for them to work properly, eg:
```javascript
(function (factory) {
  if (typeof define === 'function' && define.amd) {
    define(['jquery', 'jquery-timeago'], factory);
  } else if (typeof module === 'object' && typeof module.exports === 'object') {
    factory(require('jquery', 'jquery-timeago'));
  } else {
    factory(jQuery, jQuery.timeago);
  }
}(function (jQuery) {
  // ...
```

**Comment by rmm5t** [comment]
The locales were never really designed to be used in this way. They were designed to be used as just examples, but that has grown out of my original intention.

A PR to enhance the dependency management of locales is welcome.
