### ISSUE TITLE
Hindi Language

### ISSUE THREAD

**Issue by mohdqasim98** [rmm5t/jquery-timeago#324]
Please add locale for hindi language, or tell me how can I add it myself.

**Comment by rmm5t** [comment]
1. [Fork](https://help.github.com/articles/fork-a-repo/)
2. Create a `jquery.timeago.hi.js` template that matches the pattern of [other locales] and place it in the `locales` directory.(https://github.com/rmm5t/jquery-timeago/tree/master/locales)
3. [Commit](https://help.github.com/articles/adding-a-file-to-a-repository/)
4. [Submit a pull request](https://help.github.com/articles/creating-a-pull-request/) with the new addition.
