### ISSUE TITLE
Publish i18n files on cdnjs

### ISSUE THREAD

**Issue by tholu** [rmm5t/jquery-timeago#325]
Can you publish the i18n files also on cdnjs? https://cdnjs.com/libraries/jquery-timeago

**Comment by rmm5t** [comment]
This isn't something that I maintain or have the ability to directly publish. Your best bet is to submit a pull-request to https://github.com/cdnjs/cdnjs

https://github.com/cdnjs/cdnjs/blob/master/CONTRIBUTING.md

**Comment by tholu** [comment]
Ok then no problem, I did this before for other projects.

**Comment by rmm5t** [comment]
Cool. Thanks for understanding. I don't like to participate in distribution systems like that unless they provide a way for me to automate the publishing of new versions (either via something like `npm publish` or via something like a file in my repository that they sniff for).

**Comment by tholu** [comment]
It seems they already publish new versions automatically: https://github.com/cdnjs/cdnjs/commits/master/ajax/libs/jquery-timeago (note the commits by PeterBot)

This is configured here: https://github.com/cdnjs/cdnjs/blob/master/ajax/libs/jquery-timeago/package.json

The only thing TODO seems to be adding the locale files to the `autoupdate.fileMap.files`.

**Comment by rmm5t** [comment]
Cool. Once you get a pull-request submitted over there, point me to it, and I’ll give you a :+1: to help move it along.

**Comment by tholu** [comment]
Related issue (and PR) is here: https://github.com/cdnjs/cdnjs/issues/12242

Contributing to cdnjs has got a lot more complicated since I did this last time (40.000 commits earlier), and I'm not sure if I did this right. Let's see 😄
