### ISSUE TITLE
Refusing to work on anything except Chrome

### ISSUE THREAD

**Issue by almatrass** [rmm5t/jquery-timeago#338]
As the title says, works perfectly in Chrome, but not firefox, safari etc. Have tried everything, document ready fires as expected, then the time elements just stay blank. Any ideas?

**Comment by rmm5t** [comment]
Sounds like you're not using a ISO8601 timestamp in the original DOM element.

**Comment by rmm5t** [comment]
Please read the docs: http://timeago.yarp.com/

**Comment by almatrass** [comment]
Turns out it's working fine when I remove the milliseconds from the end of the stamp. But yet when I use milliseconds in an example JSBin in Firefox on its own it works fine, weird
