### ISSUE TITLE
jQuery.timeago is undefined when setting cutoff

### ISSUE THREAD

**Issue by mapkyca** [rmm5t/jquery-timeago#346]
```
$(document).ready(function(){
    
    jQuery.timeago.settings.cutoff = 1000*60*60*24*30;
    timeago().render($('.timeago-datetime'));

});
```
Throws TypeError: jQuery.timeago is undefined

However, comment this out and timeago().render works fine with default values. 

Is there any other way of passing parameters?

**Comment by rmm5t** [comment]
> `timeago().render($('.timeago-datetime'));`

😕`timeago()` isn't a global function. May I ask why you expected this to work?

The following is the code that I would expect to see:

```js
jQuery.timeago.settings.cutoff = 1000*60*60*24*30;
$(document).ready(function(){
  $('.timeago-datetime').timeago();
});
```
----

Btw, please take any further questions like this to a site like [StackOverflow](http://stackoverflow.com/). GitHub Issues are best reserved for discussing feature requests and bug reports.

**Comment by mapkyca** [comment]
<a href="https://github.com/rmm5t/jquery-timeago/issues/346#event-2005112212" class="u-in-reply-to"></a>Yet interestingly, it did work...

I've switched things around, but the issue still remains with setting the cutoff time complaining about jQuery...
