### ISSUE TITLE
title on abbr tag shows time, only date on time tag

### ISSUE THREAD

**Issue by LiamDawe** [rmm5t/jquery-timeago#347]
I am wondering something, the abbr tag title on hover shows date and time, but if we use the time html tag on hover the title only holds the date.

Why is this?

**Comment by rmm5t** [comment]
By default, the `title` becomes whatever was set as the original inner html value of the `abbr` or `time` tag.

However, if the original `time` tag already has a `title` attribute value, that value is preserved.

https://github.com/rmm5t/jquery-timeago/blob/master/jquery.timeago.js#L214-L216

Btw, please take any further questions like this to a site like [StackOverflow](http://stackoverflow.com/). GitHub Issues are best reserved for discussing feature requests and bug reports.
