### ISSUE TITLE
Timeago shows 2 hours ago eventhough the time is sooner

### ISSUE THREAD

**Issue by RedisMC** [rmm5t/jquery-timeago#351]
Okay, so, when I timeago for example a date that passed 1 second ago or 10 seconds or whatever less than 2 hours ago, it just shows "about 2 hours ago"

**Comment by rmm5t** [comment]
Either your server system clock is wrong, your client clock is wrong, or your timestamp formatting is wrong. Likely the latter.

**Comment by RedisMC** [comment]
This is my formatting @rmm5t 2019-04-28 15:07:02

**Comment by rmm5t** [comment]
That's not an ISO 8601 timestamp. It's missing time zone info. And it's missing the `T` delimiter (though the parser makes that optional). 

Please read the docs. 
http://timeago.yarp.com/
