### ISSUE TITLE
not work for weeks, months and years

### ISSUE THREAD

**Issue by BoumBam** [rmm5t/jquery-timeago#359]
Hello,
Bellow work fine:
`       $.timeago.settings.strings.suffixAgo = "";
	$.timeago.settings.strings.seconds = "A l'instant";
	$.timeago.settings.strings.minute = "1 m";
	$.timeago.settings.strings.minutes = "%d m";
	$.timeago.settings.strings.hour = "1 h";
	$.timeago.settings.strings.hours = "%d h";
	$.timeago.settings.strings.day = "1 jour";
	$.timeago.settings.strings.days = "%d jours";
	$("time.timeago").timeago();`

But If I try for weeks, months and years. It does not work, like bellow:
`$.timeago.settings.strings.week = "1 W";
	$.timeago.settings.strings.weeks = "%w W";
	$.timeago.settings.strings.month = "1 M";
	$.timeago.settings.strings.months = "%m M";
	$.timeago.settings.strings.year = "1 Y";
	$.timeago.settings.strings.years = "%y Y";`

Any solutions ?

Thans.

**Comment by rmm5t** [comment]
1. `week`/`weeks` is not an option
2. The substitution variable is always `%d`, never `%m` or `%y`

https://github.com/rmm5t/jquery-timeago/blob/master/jquery.timeago.js#L49-L67
