### ISSUE TITLE
Ability to toggle off/out the "about" usage for conciceness.

### ISSUE THREAD

**Issue by tchalvak** [rmm5t/jquery-timeago#63]
Part of the benefit of jquery-timeago is that it turns something silly/complicated and long like:

Created 2008-02-22, Updated 2012-03-21

into the much shorter and cleaner:

Created 4 years ago, Updated about 3 hours ago

To me, the conciseness is a great benefit, but the "about" word seems to detract from that.  Of course it wasn't updated -exactly- 3 hours ago.  I know that, you know that, everyone reading should be relatively aware of that.  As such, the "about" qualifier seems unnecessary to me, and decreases that conciseness, so it'd be nice to have a feature to turn it off.

**Comment by Jip-Hop** [comment]
This is great :) exactly what I was looking for.
I suggest mentioning this in the readme as conciseness is often very practical.
